<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ page import="java.util.*, java.text.DecimalFormat" %>
<%@ include file="header.jsp" %>

<%
    String acc = (String) request.getAttribute("accountNumber");
    String name = (String) request.getAttribute("customerName");
    Double total = (Double) request.getAttribute("totalAmount");
    Date date = (Date) request.getAttribute("billDate");
    List<Map<String, Object>> items = (List<Map<String, Object>>) request.getAttribute("bookDetails");

    DecimalFormat df = new DecimalFormat("#,##0.00");
%>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Bill Preview</title>
    <style>
        /* Include your CSS styles here or link to your external CSS */
        body {
            font-family: Arial, sans-serif;
            background-color: #f1f1f1;
            margin: 0;
            padding: 20px;
        }
        .container {
            background-color: white;
            padding: 25px;
            border-radius: 10px;
            max-width: 800px;
            margin: auto;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        .title {
            text-align: center;
            background-color: #007bff;
            color: white;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
            font-weight: bold;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        table, th, td {
            border: 1px solid #ccc;
        }
        th {
            background-color: #007bff;
            color: white;
            padding: 10px;
            text-align: left;
        }
        td {
            padding: 8px;
        }
        tfoot td {
            font-weight: bold;
            text-align: right;
            background-color: #f9f9f9;
        }
        .text-center {
            text-align: center;
        }
        .btn-print {
            background-color: #007bff;
            color: white;
            padding: 10px 25px;
            border: none;
            border-radius: 5px;
            font-size: 16px;
            cursor: pointer;
            margin-top: 20px;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
        .btn-print:hover {
            background-color: #0056b3;
        }
         @media print { .app-header { display: none !important; } .btn-print, .submit-btn, .logout-link, .help-link { display: none !important; } body { margin: 0; background: white; } }
    </style>
</head>
<body>
<div class="container">
    <h3 class="title">Bill Preview</h3>

    <div>
        <p><strong>Customer Name:</strong> <%= (name != null) ? name : "Unknown Customer" %></p>
        <p><strong>Account Number:</strong> <%= (acc != null) ? acc : "N/A" %></p>
        <p><strong>Date:</strong> <%= (date != null) ? new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(date) : "N/A" %></p>
    </div>

    <div class="mt-3">
        <p><strong>Generated By:</strong> <%= (username != null) ? username : "Unknown User" %></p>
    </div>

    <table>
        <thead>
        <tr>
            <th>#</th>
            <th>Book Title</th>
            <th>Qty</th>
            <th>Unit Price (LKR)</th>
            <th>Total (LKR)</th>
        </tr>
        </thead>
        <tbody>
        <%
            int i = 1;
            if (items != null) {
                for (Map<String, Object> item : items) {
        %>
        <tr>
            <td><%= i++ %></td>
            <td><%= item.get("title") %></td>
            <td><%= item.get("qty") %></td>
            <td><%= df.format(item.get("unitPrice")) %></td>
            <td><%= df.format(item.get("total")) %></td>
        </tr>
        <%
                }
            } else {
        %>
        <tr><td colspan="5" class="text-center">No items found</td></tr>
        <%
            }
        %>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="4" class="text-right">Grand Total</td>
            <td><%= (total != null) ? df.format(total) : "0.00" %></td>
        </tr>
        </tfoot>
    </table>

    <button class="btn-print" onclick="window.print()">Print Bill</button>
</div>
</body>
</html>
	