<%@ page import="java.util.*, java.text.DecimalFormat" %>
<%@ page import="com.pahanaedu.model.Bill" %>
<%@ include file="header.jsp" %>
<%@ page contentType="text/html;charset=UTF-8" %>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>All Bills</title>
    <link rel="stylesheet" type="text/css" href="css/styleBill.css"> <!-- Update as per your actual CSS file -->
</head>
<body>

<div class="container">
    <h2 class="title">All Bills</h2>

    <% if ("admin".equalsIgnoreCase(admin)) { %>
    <div class="form-group">
        <a href="adminPanel.jsp" class="submit-btn" style="text-decoration:none;">Back to Admin Panel</a>
    </div>
    <% } %>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Customer</th>
                <th>Books Purchased</th>
                <th>Total Amount (LKR)</th>
                <th>Bill Date</th>
                <th>Invoice Generated By</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        <%
            List<Bill> salesList = (List<Bill>) request.getAttribute("billList");
            DecimalFormat df = new DecimalFormat("#,##0.00");
            int count = 1;

            if (salesList != null && !salesList.isEmpty()) {
                for (Bill sale : salesList) {
        %>
            <tr>
                <td><%= count++ %></td>
                <td><%= sale.getCustomerName() %> (<%= sale.getAccountNumber() %>)</td>
                <td><%= sale.getBooksPurchased() %></td>
                <td><%= df.format(sale.getTotalAmount()) %></td>
                <td><%= sale.getBillingTime() %></td>
                <td><%= sale.getStaffUsername() %></td>

                <% if (!"Cashier".equalsIgnoreCase(role) && !"Manager".equalsIgnoreCase(role)) { %>
                <td>
                    <a href="BillController?action=delete&id=<%= sale.getId() %>" class="btn-delete"
                       onclick="return confirm('Are you sure you want to delete this bill?');">
                        Delete
                    </a>
                </td>
                <% } else { %>
                <td class="readonly">No actions allowed for <%= role %> (Refer Admin)</td>
                <% } %>
            </tr>
        <%
                }
            } else {
        %>
            <tr>
                <td colspan="7" class="center-align">No sales records found.</td>
            </tr>
        <% } %>
        </tbody>
    </table>

    <% if (salesList != null) { %>
    <div class="form-group right-align" style="margin-top: 20px;">
        <strong>Total Invoices: <%= salesList.size() %></strong>
    </div>
    <% } %>
</div>

</body>
</html>
