<%@ page import="java.util.*, java.text.DecimalFormat" %>
<%@ page import="com.pahanaedu.model.Bill" %>
<%@ include file="header.jsp" %>
<%@ page contentType="text/html;charset=UTF-8" %>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>All Bills</title>
    <link rel="stylesheet" type="text/css" href="css/styleBill.css"> <!-- Update as per your actual CSS file -->
</head>
<body>

<div class="container">
    <h2 class="title">All Bills</h2>
    	


	   
	    <% if ("admin".equalsIgnoreCase(admin)) { %>
	    <div class="form-group">
	        <a href="adminPanel.jsp" class="admin-btn" style="text-decoration:none;">Back to Admin Panel</a>
	    </div>
	    <% } %>
	    
	<div class="div-search">
	
		<form method="get" action="BillController">
		    <input type="hidden" name="action" value="list" />
		
		    Customer Account: 
		    <input type="text" name="account" value="<%= request.getParameter("account") != null ? request.getParameter("account") : "" %>" />
		    
		    Invoice Number: 
		    <input type="text" name="invoicenum" style="max-width:30px;" value="<%= request.getParameter("invoicenum") != null ? request.getParameter("invoicenum") : "" %>" />
		    
		<br>
		    From: 
		    <input type="date" name="from" value="<%= request.getParameter("from") != null ? request.getParameter("from") : "" %>" />
		
		    To: 
		    <input type="date" name="to" value="<%= request.getParameter("to") != null ? request.getParameter("to") : "" %>" />
		
		    <input type="submit" value="Filter"/>
		    <br><br>
		    <a href="BillController?action=list" style="text-decoration:none;">
 			 <button type="button" class="clear-btn">Clear Filters</button>
			</a>
	     
		</form> 

	</div>


    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Invoice Number</th>
                <th>Customer</th>
                <th>Books Purchased</th>
                <th>Total Amount (LKR)</th>
                <th>Bill Date</th>
                <th>Invoice Generated By</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
        <%
            List<Bill> salesList = (List<Bill>) request.getAttribute("billList");
            DecimalFormat df = new DecimalFormat("#,##0.00");
            int count = 1;
            double totalSales = 0.0;

            if (salesList != null && !salesList.isEmpty()) {
                for (Bill sale : salesList) {
                	totalSales += sale.getTotalAmount();
        %>
            <tr>
                <td><%= count++ %></td>
                <td style="background-color:Yellow; text-align:center;"><%= sale.getId() %></td>
                <td><%= sale.getCustomerName() %> (<%= sale.getAccountNumber() %>)</td>
                <td><%= sale.getBooksPurchased() %></td>
                <td style="text-align:right"><%= df.format(sale.getTotalAmount()) %></td>
                <td><%= sale.getBillingTime() %></td>
                <td style="text-align:center"><%= sale.getStaffUsername() %></td>

                <% if (!"Cashier".equalsIgnoreCase(role) && !"Manager".equalsIgnoreCase(role)) { %>
                <td>
                    <a href="BillController?action=delete&id=<%= sale.getId() %>" class="btn-delete"
                       onclick="return confirm('Are you sure you want to delete this bill?');">
                        Delete
                    </a>
                </td>
                <% } else { %>
                <td class="readonly">No actions allowed for <%= role %> (Refer Admin)</td>
                <% } %>
            </tr>
        <%
                }
            } else {
        %>
            <tr>
                <td colspan="7" class="center-align">No sales records found.</td>
            </tr>
        <% } %>
        </tbody>
    </table>

    <% if (salesList != null) { %>
    <div class="form-group right-align" style="margin-top: 20px;">
        <strong>Total Invoices: <%= salesList.size() %></strong> <br>
   		<strong>Total Sales (LKR): <%= df.format(totalSales) %></strong>
    </div>
    <% } %>
</div>

</body>
</html>
